baseURL       = "https://atrandah.github.io/site"
title         = "Alicja Tranda"
summarylength = 25

defaultContentLanguage = 'en'
defaultContentLanguageInSubdir = true

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[params]
  logo = "images/logo.png"
  logo_footer = "images/logo.png"
  favicon_icon = "images/favicon.ico"
  favicon_shortcut_icon = "images/favicon.png"
  custom_stylesheets = [ "scss/_variables.scss" ]
  dateFormat = "26 FEB 1994"
  author = "Alicja Tranda"
  googleAnalitycsID = "Your ID"
  fabform  = "https://fabform.io/f/xM-wwPg"

  [params.banner]
    hero_image = "images/hero.jpg"

  [params.video]
    enable    = true
    video_url = "https://www.youtube.com/embed/T27XggtdVaQ"

  [params.bio]
    bio_image = "images/bio.jpg"

  [params.lessons]
    lessons_image = "images/lessons.jpg"

  [params.call_to_action]
    enable           = true
    background_image = "images/backgrounds/cta-background.jpg"

  [params.footer.contact]
    email = "hello@alicjatranda.com"

    [[params.footer.contact.link]]
      name = "Facebook"
      url  = "https://www.facebook.com/AlicjaTrandaVocalCoach"
    [[params.footer.contact.link]]
      name = "Instagram"
      url  = "https://www.instagram.com/alicjatranda.vocalcoach/"
    [[params.footer.contact.link]]
      name = "YouTube"
      url  = "https://www.youtube.com/@alicjatrandamusic"

[languages]
  [languages.en]
    contentDir = 'content/english'
    locale = 'EN'
    label = 'English'
    weight = 1

    [languages.en.params]
      description = "Alicja Tranda - vocal coach and vocalist based in Lodz, Poland (EU)"

      [languages.en.params.contactForm]
        placeholder_first_name = "First Name"
        placeholder_last_name  = "Last Name"
        placeholder_email      = "Email"
        placeholder_phone      = "Phone"
        placeholder_message    = "Message"
        send_message           = "Send"

      [languages.en.params.navAction]
        status = true
        name   = "Get in touch"
        url    = "contact"

      [languages.en.params.banner]
        enable             = true
        heading            = "Alicja Tranda"
        description        = "Vocal coach and vocalist based in Lodz, Poland (EU)."
        primary_button     = "Contact"
        primary_button_url = "contact"

      [languages.en.params.statement]
        enable  = true
        heading = "Free your voice with me"
        content = """
          Do you feel your voice cannot reach its full potential? Do you
          struggle with high notes and strain your voice? Do you need more
          power… or you have a powerful voice, but cannot control it? Do you
          dream of a free, capable voice with vast range - ready for stage and
          studio demands?  Let me guide you in this process of building a strong
          foundation for your artistic development. I work with singers who want
          to unlock the best in their voices. I believe everyone can sing - you
          need a tailored practice to blossom truly.
          """

      [languages.en.params.bio]
        enable             = true
        heading            = "About me"
        primary_button     = "Full bio"
        primary_button_url = "about"
        content            = """
          Alicja is a vocalist and vocal coach specialising in contemporary and
          rock vocal performance. She is a Level 3 Modern Vocal Training coach
          with several years of experience, working with singers at all levels,
          individually and in groups. Alicja is constantly improving her skills
          under the supervision of specialists from around the world, studying
          diverse approaches to voice. Her additional professional training
          includes courses in music production and songwriting. As a vocalist,
          dancer and actress, she has performed in theatre productions,
          concerts, and experimental art projects. Currently, Alicja is
          co-founding Ekstremalna Szkoła Wokalna (Extreme Vocal School) in Lodz
          and continues to develop her own artistic work.
          """

      [languages.en.params.lessons]
        enable             = true
        heading            = "Vocal coaching  for singers / online lessons"
        primary_button     = "Sign me in"
        primary_button_url = "lessons"
        content            = """
          No matter how experienced you are, together we will find solutions to
          improve your voice. During lessons, we work toward your goals - every lesson is
          created for your growth. Your vocal abilities expand through scales, song
          fragments, and many other exercises. You will learn how to work on your voice
          between our sessions, becoming more aware of your vocal health, growing your
          stamina, and overcoming stage fright! My role as a vocal coach is to create an
          environment where you can develop your unique sound and explore new
          possibilities.
          """

      [languages.en.params.call_to_action]
        enable               = true
        title                = "LET’S WORK TOGETHER"
        primary_button       = "Submit Query"
        primary_button_url   = "contact"
        secondary_button     = "Not Convinced"
        secondary_button_url = "portfolio"

      [languages.en.params.footer]
        qr_print = false

        [languages.en.params.footer.contact]
          title = "Contact"

        [languages.en.params.footer.other]
          title       = "ESW"
          description = "Do you need a stationary in-person lesson? You will find me here!"
          url         = "ekstremalnaszkolawokalna.pl"
          address     = "Piwna 24, Łódź, Poland"

        [languages.en.params.footer.service]
          title       = "Online lessons"
          description = "I also offer online lessons. Learn from anywhere. I'll adjust the schedule to fit you."

        [languages.en.params.footer.back_to_top]
          description = "I want to <br> visit again"

  [languages.pl]
    contentDir = 'content/polish'
    locale = 'PL'
    label = 'Polish'
    weight = 2

    [languages.pl.params]
      description = "Alicja Tranda - nauczycielka śpiewu i wokalistka z Łodzi (Polska, UE)"

      [languages.pl.params.contactForm]
        placeholder_first_name = "First Name"
        placeholder_last_name  = "Last Name"
        placeholder_email      = "Email"
        placeholder_phone      = "Phone"
        placeholder_message    = "Message"
        send_message           = "Send"

      [languages.pl.params.navAction]
        status = true
        name   = "Get in touch"
        url    = "contact"

      [languages.pl.params.banner]
        enable             = true
        heading            = "Alicja Tranda"
        description        = "Nauczycielka śpiewu i wokalistka z Łodzi (Polska, UE)."
        primary_button     = "Kontakt"
        primary_button_url = "contact"

      [languages.pl.params.statement]
        enable  = true
        heading = "Uwolnij swój głos ze mną"
        content = """
          Czujesz, że Twój głos nie wykorzystuje pełni swojego potencjału? Masz
          trudności z wysokimi dźwiękami i nadwyrężasz głos? Potrzebujesz więcej
          mocy… a może masz mocny głos, ale nie potrafisz nad nim zapanować?
          Marzysz o wolnym, sprawnym głosie o szerokiej skali - gotowym na
          wyzwania sceny i studia? Pozwól, że poprowadzę Cię w procesie budowania
          solidnych podstaw Twojego artystycznego rozwoju. Pracuję z wokalistami,
          którzy chcą wydobyć ze swojego głosu to, co najlepsze. Wierzę, że każdy
          może śpiewać - potrzebujesz jedynie praktyki dopasowanej do Ciebie, by
          w pełni rozkwitnąć.
          """

      [languages.pl.params.bio]
        enable             = true
        heading            = "O mnie"
        primary_button     = "Pełne bio"
        primary_button_url = "about"
        content            = """
          Alicja jest wokalistką i trenerką wokalną specjalizującą się we
          współczesnym i rockowym śpiewie. Jest trenerką Modern Vocal Training na
          poziomie 3 z wieloletnim doświadczeniem, pracującą z wokalistami na
          każdym poziomie zaawansowania, indywidualnie i w grupach. Alicja
          nieustannie doskonali swoje umiejętności pod okiem specjalistów z całego
          świata, zgłębiając różnorodne podejścia do pracy z głosem. Jej
          dodatkowe szkolenia zawodowe obejmują kursy z produkcji muzycznej i
          pisania piosenek. Jako wokalistka, tancerka i aktorka występowała w
          spektaklach teatralnych, koncertach i eksperymentalnych projektach
          artystycznych. Obecnie Alicja współtworzy Ekstremalną Szkołę Wokalną w
          Łodzi i wciąż rozwija swoją własną twórczość artystyczną.
          """

      [languages.pl.params.lessons]
        enable             = true
        heading            = "Trening wokalny dla wokalistów / lekcje online"
        primary_button     = "Zapisz mnie"
        primary_button_url = "lessons"
        content            = """
          Niezależnie od Twojego doświadczenia, wspólnie znajdziemy rozwiązania,
          które poprawią Twój głos. Podczas lekcji pracujemy nad Twoimi celami -
          każda lekcja jest tworzona z myślą o Twoim rozwoju. Twoje możliwości
          wokalne poszerzają się dzięki skalom, fragmentom piosenek i wielu innym
          ćwiczeniom. Nauczysz się, jak pracować nad głosem między naszymi
          spotkaniami, stając się bardziej świadomy zdrowia swojego głosu,
          budując wytrzymałość i pokonując tremę! Moją rolą jako trenerki wokalnej
          jest stworzenie przestrzeni, w której możesz rozwijać swoje unikalne
          brzmienie i odkrywać nowe możliwości.
          """

      [languages.pl.params.call_to_action]
        enable               = true
        heading              = "LET’S WORK TOGETHER"
        primary_button       = "Submit Query"
        primary_button_url   = "contact"
        secondary_button     = "Not Convinced"
        secondary_button_url = "portfolio"

      [languages.pl.params.footer]
        qr_print = false

        [languages.pl.params.footer.contact]
          title = "Kontakt"

        [languages.pl.params.footer.other]
          title       = "ESW"
          description = "Potrzebujesz stacjonarnej lekcji na żywo? Znajdziesz mnie tutaj!"
          url         = "ekstremalnaszkolawokalna.pl"
          address     = "Piwna 24, Łódź, Poland"

        [languages.pl.params.footer.service]
          title       = "Lekcje online"
          description = "Oferuję również lekcje online. Ucz się z dowolnego miejsca. Terminy dopasuję do Ciebie."

        [languages.pl.params.footer.back_to_top]
          description = "Wróć na górę"
